version: '3'
services:

  gogreen-sql-db:
    container_name: gogreen-sql-db
    image: mcr.microsoft.com/mssql/server
    volumes:
      - ./data:/var/lib/mysql
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Password1$
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    expose:
      - 1433
    networks:
      - gogreen-vlan

  gogreen-api:
    container_name: gogreen-api
    restart: unless-stopped
    build:
      context: .
    env_file:
      - .env
    environment:
      - ConnectionStrings:DefaultConnection=Server=gogreen-sql-db,1433;Database=gogreen;User=sa;Password=Password1$;ConnectRetryCount=0; TrustServerCertificate=True
      - RabbitMQConfig__HostName=gogreen-rabbitmq
      - RabbitMQConfig__Port=5672
      - RabbitMQConfig__UserName=admin
      - RabbitMQConfig__Password=password
      - RabbitMQConfig__defaultQueue=my_queue
      - AzureStorage__ConnectionString=${AzureStorage__ConnectionString}
      - Mailgun__apiKey=${Mailgun__apiKey}
      - Mailgun__domain=${Mailgun__domain}
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:8080"
    networks:
      - gogreen-vlan
    depends_on:
      - gogreen-sql-db

  gogreen-rabbitmq:
    container_name: gogreen-rabbitmq
    image: rabbitmq:3.9.5
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    networks:
      - gogreen-vlan

  communication-service:
    container_name: communication-service
    build:
      context: .   # Set the correct path to your Communication.Service project
      dockerfile: Dockerfile-Communication.Service
    env_file:
      - .env  # If needed, provide an environment file for Communication.Service
    environment:
      - RabbitMQConfig__HostName=gogreen-rabbitmq
      - RabbitMQConfig__Port=5672
      - RabbitMQConfig__UserName=admin
      - RabbitMQConfig__Password=password
      - RabbitMQConfig__defaultQueue=my_queue
      - Mailgun__apiKey=${Mailgun__apiKey}
      - Mailgun__domain=${Mailgun__domain}
      - ASPNETCORE_ENVIRONMENT=Production
    networks:
      - gogreen-vlan
    depends_on:
      - gogreen-rabbitmq

networks:
  gogreen-vlan:
    driver: bridge      